import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, extname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import { writeLine } from "../io.js";
import { resolveDefaultAppPath } from "../project.js";
import type { CliIo } from "../types.js";

const execFileAsync = promisify(execFile);

export interface GenerateClientCommandOptions {
  app?: string | undefined;
  output?: string | undefined;
  actionsExport: string;
  exportName: string;
}

export async function runGenerateClientCommand(args: string[], cwd: string, io: CliIo): Promise<number> {
  const options = parseGenerateClientArgs(args);
  const appPath = options.app ?? (await resolveDefaultAppPath(cwd));
  const outputPath = options.output ?? "src/generated/client.ts";
  const resolvedAppPath = resolve(cwd, appPath);
  const resolvedOutputPath = resolve(cwd, outputPath);

  await validateActionsExport(resolvedAppPath, options.actionsExport);

  const source = createClientModuleSource({
    outputPath: resolvedOutputPath,
    appPath: resolvedAppPath,
    actionsExport: options.actionsExport,
    exportName: options.exportName,
  });

  await mkdir(dirname(resolvedOutputPath), { recursive: true });
  await writeFile(resolvedOutputPath, source);

  writeLine(io, `Wrote typed client module to ${outputPath}`);

  return 0;
}

function parseGenerateClientArgs(args: string[]): GenerateClientCommandOptions {
  const options: GenerateClientCommandOptions = {
    actionsExport: "actions",
    exportName: "createApiClient",
  };

  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    const nextValue = args[index + 1];

    if (nextValue === undefined) {
      throw new Error(`Missing value for ${argument}`);
    }

    switch (argument) {
      case "--app":
        options.app = nextValue;
        break;
      case "--output":
        options.output = nextValue;
        break;
      case "--actions-export":
        options.actionsExport = nextValue;
        break;
      case "--export-name":
        options.exportName = nextValue;
        break;
      default:
        throw new Error(`Unknown option: ${argument}`);
    }

    index += 1;
  }

  return options;
}

async function validateActionsExport(appPath: string, actionsExport: string): Promise<void> {
  const workerPath = resolveWorkerPath();

  await execFileAsync(process.execPath, ["--import", "tsx", workerPath, appPath, actionsExport]);
}

function createClientModuleSource(options: {
  outputPath: string;
  appPath: string;
  actionsExport: string;
  exportName: string;
}): string {
  const appImportPath = toImportPath(relative(dirname(options.outputPath), options.appPath));

  return `/* eslint-disable */
/* This file is auto-generated by Action.js. Do not edit manually. */

import { createClient, type ClientFromTree, type CreateClientOptions } from "@action-js/client";
import { ${options.actionsExport} } from "${appImportPath}";

export type ApiClient = ClientFromTree<typeof ${options.actionsExport}>;

export function ${options.exportName}(
  options: Omit<CreateClientOptions<typeof ${options.actionsExport}>, "actions">,
): ApiClient {
  return createClient({
    ...options,
    actions: ${options.actionsExport},
  });
}

export { ${options.actionsExport} };
`;
}

function resolveWorkerPath(): string {
  const currentFilePath = fileURLToPath(import.meta.url);
  const currentExtension = extname(currentFilePath);

  return fileURLToPath(new URL(`../client-worker${currentExtension}`, import.meta.url));
}

function toImportPath(relativePath: string): string {
  const normalized = relativePath.split(sep).join("/");
  const withPrefix = normalized.startsWith(".") ? normalized : `./${normalized}`;

  if (withPrefix.endsWith(".ts")) {
    return `${withPrefix.slice(0, -3)}.js`;
  }

  if (withPrefix.endsWith(".js")) {
    return withPrefix;
  }

  return `${withPrefix}.js`;
}
