import { action, type ActionDefinition, type ActionResponseDefinitions, type HttpMethod } from "@action-js/core";
import { z } from "zod";

import { createOpenApiDocument } from "./document.js";
import type { OpenApiDocument, OpenApiInfo, OpenApiServer } from "./types.js";

type AnyAction = ActionDefinition<HttpMethod, string, any, any, any, any, any, any, any>;

type PluginAction<TServices, TContext extends object> = ActionDefinition<
  HttpMethod,
  string,
  TServices,
  TContext,
  any,
  any,
  any,
  ActionResponseDefinitions | undefined,
  any
>;

export interface OpenApiPlugin<TServices, TContext extends object = {}> {
  name: string;
  actions?: ReadonlyArray<PluginAction<TServices, TContext>> | undefined;
}

export interface OpenApiPluginOptions {
  info: OpenApiInfo;
  actions: ReadonlyArray<AnyAction> | (() => ReadonlyArray<AnyAction>);
  servers?: OpenApiServer[] | undefined;
  jsonPath?: string | undefined;
  docsPath?: string | undefined;
}

export function openApiPlugin<TServices, TContext extends object = {}>(
  options: OpenApiPluginOptions,
): OpenApiPlugin<TServices, TContext> {
  const jsonPath = options.jsonPath ?? "/openapi.json";
  const docsPath = options.docsPath ?? "/docs";

  return {
    name: "openapi",
    actions: [
      action({
        method: "GET",
        path: jsonPath,
        response: {
          200: z.any(),
        },
        handler: () => ({
          status: 200 as const,
          body: createDocument(options),
        }),
      }),
      action({
        method: "GET",
        path: docsPath,
        handler: () =>
          new Response(renderDocsHtml(options.info.title, jsonPath), {
            status: 200,
            headers: {
              "content-type": "text/html; charset=utf-8",
            },
        }),
      }),
    ],
  };
}

function createDocument(options: OpenApiPluginOptions): OpenApiDocument {
  return createOpenApiDocument({
    info: options.info,
    actions: resolveActions(options.actions),
    servers: options.servers,
  });
}

function resolveActions(actions: OpenApiPluginOptions["actions"]): ReadonlyArray<AnyAction> {
  return typeof actions === "function" ? actions() : actions;
}

function renderDocsHtml(title: string, jsonPath: string): string {
  const safeTitle = escapeHtml(title);
  const safeJsonPath = escapeHtml(jsonPath);

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${safeTitle} Docs</title>
    <style>
      :root {
        color-scheme: dark;
        font-family: Inter, ui-sans-serif, system-ui, sans-serif;
        background: #0b1020;
        color: #e5edf7;
      }

      body {
        margin: 0;
        padding: 2rem;
        background:
          radial-gradient(circle at top left, rgba(56, 189, 248, 0.22), transparent 35%),
          radial-gradient(circle at top right, rgba(168, 85, 247, 0.18), transparent 30%),
          #0b1020;
      }

      .shell {
        max-width: 1080px;
        margin: 0 auto;
        display: grid;
        gap: 1rem;
      }

      .hero,
      .panel {
        background: rgba(10, 15, 30, 0.8);
        border: 1px solid rgba(148, 163, 184, 0.2);
        border-radius: 20px;
        backdrop-filter: blur(14px);
      }

      .hero {
        padding: 1.5rem;
      }

      h1 {
        margin: 0 0 0.5rem;
        font-size: clamp(2rem, 5vw, 3.5rem);
      }

      p {
        margin: 0;
        color: #b8c5d6;
      }

      .panel {
        padding: 1rem;
      }

      pre {
        margin: 0;
        overflow: auto;
        white-space: pre-wrap;
        word-break: break-word;
        font-size: 0.95rem;
        line-height: 1.5;
      }

      .meta {
        margin-top: 0.75rem;
        font-size: 0.9rem;
      }

      a {
        color: #7dd3fc;
      }
    </style>
  </head>
  <body>
    <main class="shell">
      <section class="hero">
        <h1>${safeTitle}</h1>
        <p>Generated by Action.js from your action contracts.</p>
        <p class="meta">Raw spec: <a href="${safeJsonPath}">${safeJsonPath}</a></p>
      </section>
      <section class="panel">
        <pre id="spec">Loading OpenAPI document...</pre>
      </section>
    </main>
    <script>
      fetch(${JSON.stringify(jsonPath)})
        .then((response) => response.json())
        .then((document) => {
          document.getElementById("spec").textContent = JSON.stringify(document, null, 2);
        })
        .catch((error) => {
          document.getElementById("spec").textContent = "Failed to load OpenAPI document: " + String(error);
        });
    </script>
  </body>
</html>`;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}
